// Official advisor list — matches the department's Google Form.
export const ADVISORS: string[] = [
  "ศ.ดร.มนตรี ชูวงษ์ (Prof. Dr. Montree Chuwong)",
  "ศ.ดร.จักรพันธ์ สุทธิรัตน์ (Prof. Dr. Chakkaphan Suthirat)",
  "ศ.ดร.พิษณุพงศ์ กาญจนพยนต์ (Prof. Dr. Pitsanupong Kanchanapayon)",
  "ศ.ดร.ศรีเลิศ โชติพันธรัตน์ (Prof. Dr. Srilert Chotipantarat)",
  "รศ.ดร.ฐาสิณีย์ เจริญฐิติรัตน์ (Assoc. Prof. Dr. Thasinee Charoenthitirat)",
  "ศ.ดร.สันติ ภัยหลบลี้ (Prof. Dr. Santi Pailoplee)",
  "รศ.ดร.ฐานบ ธิติมากร (Assoc. Prof. Dr. Thanob Thitimakorn)",
  "ผศ.ดร.วิชัย จูฑะโกสิทธิ์กานนท์ (Asst. Prof. Dr. Wichai Jutakositkanon)",
  "รศ.ดร.อัคนีวุธ จิรภิญญากุล (Assoc. Prof. Dr. Akaneewut Jirapinyakul)",
  "รศ.ดร.ปิยพงษ์ เชนร้าย (Assoc. Prof. Dr. Piyapong Chenrai)",
  "ผศ.ดร.สุเมธ พันธุวงค์ราช (Asst. Prof. Dr. Sumeth Phanthuwongrach)",
  "รศ.ดร.สุคนธ์เมธ จิตรมหันตกุล (Assoc. Prof. Dr. Sukonmeth Jitramahuntakul)",
  "ศ.ดร.สกลวรรณ ชาวไชย (Prof. Dr. Sakonwan Chaochai)",
  "รศ.ดร.กันตภณ สุระประสิทธิ์ (Assoc. Prof. Dr. Kantaphon Suraprasit)",
  "รศ.ดร.ฐิติพรรณ อัศวินเจริญกิจ (Assoc. Prof. Dr. Thitiphan Assawincharoenkit)",
  "ผศ.ดร.อลงกต ฝั้นกา (Asst. Prof. Dr. Alongkot Fanka)",
  "อ.ดร.พงศ์เทพ ทองแสง (Dr. Pongthep Thongsang)",
  "อ.ดร.สิรวิชญ์ แก้วผลึก (Dr. Sirawit Khawpaluk)",
  "อ.ดร.ศิรวัชร์ อุดมศักดิ์ (Dr. Sirawat Udomsak)",
  "อ.ดร.ภคิน อัศวภาณุวัฒน์ (Dr. Prakhin Assavapanuvat)",
  "อ.ดร.บุญฑิกานต์ คูหาสรรพสิน (Dr. Boontigan Kuhasubpasin)",
];
